name: integration

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build && yarn build:test

      - name: Lint
        run: yarn lint

      - name: Test extension
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:desktop

      - name: Test web extension
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:web
